---
#   Copyright 2022 IBM Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# defaults variables file for install_saphostagent

# Temporary directory path, that will be created on the target host
insshagnt_dir_temp_managednode: "/tmp/hostctrl"

# Directory path on the Ansible host where SAR file is located
insshagnt_dir_download_managednode: "/tmp/downloads"

# Directory on the target host where SAPCAR is searched by default
insshagnt_dir_sapcar_default_managednode: "/usr/sap/hostctrl/exe"

# Default SAPCAR file name
insshagnt_file_sapcar: "SAPCAR"

# Boolean variable to indicate if the temporary directory on the target host will be removed or not after the installation
insshagnt_bool_clean_dir_temp_managednode: True
